**TUGAS PRAKTIKUM 5 INFORMATION RETRIEVAL**

Nama    : Suhendra Widi Prayoga

NIM     : 222112382

Kelas   : 3SD2

PREPROCESSING

In [12]:
# Import Module
import os 
from spacy.lang.id import Indonesian

nlp = Indonesian()  # Load Indonesian language model

# Folder Path
path = "D:/POLITEKNIK STATISTIKA STIS 63/python/berita"

# Function to read text file
def read_text_file(file_path):
    with open(file_path, 'r') as f:
        content = f.read()
    return content

# iterate through all file
i = 0
berita = {}
for file in os.listdir(path):
    # Check whether file is in text format or not
    if file.endswith(".txt"):
        #print kalimat berita ke-i
        file_path = f"{path}\{file}"
        # call read text file function
        berita[i] = read_text_file(file_path)
        i = i + 1

# Case-Folding Isi File Berita
case_folding = {}
for key in berita:
    case_folding[key] = berita[key].lower()

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

# Membuat objek stemmer dari Sastrawi
factory = StemmerFactory()
stemmer = factory.create_stemmer()

# Melakukan stemming untuk indeks 0 hingga 4
stemming = {}
for key in range(5):  # Mulai dari indeks 0 hingga 4
    stemming[key] = stemmer.stem(case_folding[key])

import spacy

# Membuat objek NLP dengan model bahasa Indonesia
nlp = spacy.blank('id')

tokenisasi = {}

# Mengganti pemanggilan fungsi tokenisasi
for key in range(5):
    spacy_doc = nlp(stemming[key])
    tokenized_text = [token.text for token in spacy_doc]
    tokenisasi[key] = tokenized_text

from spacy.lang.id import Indonesian

# Membuat objek NLP dengan model bahasa Indonesia
nlp = Indonesian()
nlp = spacy.blank('id')

stopwords = nlp.Defaults.stop_words
hasil_stopword = {}

for key in range(5):  # Melakukan eliminasi stopword untuk indeks 0 hingga 4
    # Menggunakan SpaCy untuk menghapus stopword
    tokens = tokenisasi[key]
    tokens_tanpa_stopword = [w for w in tokens if w.lower() not in stopwords]
    
    # Simpan hasil eliminasi stopword dalam kamus
    hasil_stopword[key] = tokens_tanpa_stopword

# Daftar term dari hasil stopword (indeks ke-0 hingga ke-4)
corpus_term = [hasil_stopword[0],hasil_stopword[1],hasil_stopword[2],hasil_stopword[3],hasil_stopword[4]]

# Membuat inverted index dengan term yang sudah di-stem
inverted_index = {}
for i in range(len(corpus_term)):
    for item in corpus_term[i]:
            if item not in inverted_index:
                inverted_index[item] = []
            if (item in inverted_index) and ((i+1) not in inverted_index[item]):
                inverted_index[item].append(i+1)

# Print inverted index
print("Inverted Index:")
print(inverted_index)

Inverted Index:
{'wilayah': [1, 5], 'bebas': [1], 'covid': [1, 2, 3, 4, 5], '-': [1, 2, 3, 4, 5], '19': [1, 2, 3, 4, 5], 'cek': [1], '34': [1], 'kab': [1], 'kota': [1], 'zona': [1], 'hijau': [1], 'jakarta': [1, 2, 3, 4, 5], 'perintah': [1], 'rencana': [1, 2], 'terap': [1], 'laku': [1, 2], 'batas': [1], 'giat': [1], 'masyarakat': [1], 'ppkm': [1], 'level': [1], '3': [1], 'hitung': [1], '24': [1], 'desember': [1], '2021': [1, 5], '2': [1, 3], 'januari': [1, 2], 'menteri': [1], 'sehat': [1], 'ri': [1, 3, 4], 'bijak': [1], 'tahap': [1], 'kaji': [1], 'direktur': [1], 'cegah': [1], 'kendali': [1], 'sakit': [1], 'tular': [1], 'langsung': [1, 2, 3], 'p2pml': [1], 'kemenkes': [1, 4], 'dr': [1, 5], 'siti': [1], 'nadia': [1], 'tarmizi': [1], 'signifikan': [1, 4], 'picu': [1], 'tingkat': [1, 4], 'mobilitas': [1], 'longgar': [1], 'protokol': [1], 'https': [1, 2, 3, 4, 5], 'health': [1, 2, 3, 4, 5], 'detik': [1, 2, 3, 4, 5], 'com': [1, 2, 3, 4, 5], 'berita': [1, 2, 3, 4, 5], 'detikhealth': [1, 2, 3,

**Nomor 1**

Buat fungsi main untuk menampilkan 3 list dokumen yang terurut berdasarkan cosine similarity pada folder ”berita” dengan query "vaksin corona jakarta”.

In [13]:
# Membuat inverted index dengan term yang sudah di-tokenisasi
inverted_index = {}
for doc_id, tokens in hasil_stopword.items():
    doc_label = f"berita{doc_id + 1}"  # Menggunakan label berita1, berita2, dst.
    for token in tokens:
        if token not in inverted_index:
            inverted_index[token] = []
        if doc_label not in inverted_index[token]:
            inverted_index[token].append(doc_label)

print(inverted_index)


{'wilayah': ['berita1', 'berita5'], 'bebas': ['berita1'], 'covid': ['berita1', 'berita2', 'berita3', 'berita4', 'berita5'], '-': ['berita1', 'berita2', 'berita3', 'berita4', 'berita5'], '19': ['berita1', 'berita2', 'berita3', 'berita4', 'berita5'], 'cek': ['berita1'], '34': ['berita1'], 'kab': ['berita1'], 'kota': ['berita1'], 'zona': ['berita1'], 'hijau': ['berita1'], 'jakarta': ['berita1', 'berita2', 'berita3', 'berita4', 'berita5'], 'perintah': ['berita1'], 'rencana': ['berita1', 'berita2'], 'terap': ['berita1'], 'laku': ['berita1', 'berita2'], 'batas': ['berita1'], 'giat': ['berita1'], 'masyarakat': ['berita1'], 'ppkm': ['berita1'], 'level': ['berita1'], '3': ['berita1'], 'hitung': ['berita1'], '24': ['berita1'], 'desember': ['berita1'], '2021': ['berita1', 'berita5'], '2': ['berita1', 'berita3'], 'januari': ['berita1', 'berita2'], 'menteri': ['berita1'], 'sehat': ['berita1'], 'ri': ['berita1', 'berita3', 'berita4'], 'bijak': ['berita1'], 'tahap': ['berita1'], 'kaji': ['berita1'], 

In [14]:
vocab = []
inverted_index = {}

# Daftar dokumen dengan label "berita1", "berita2", hingga "berita5"
doc_labels = ["berita1", "berita2", "berita3", "berita4", "berita5"]

for doc_id, tokens in tokenisasi.items():
    doc_label = doc_labels[doc_id]  # Mengambil label dokumen dari daftar doc_labels
    for token in tokens:
        print(token)
        if token not in vocab:
            vocab.append(token)
            inverted_index[token] = []
        if token in inverted_index:
            if doc_label not in inverted_index[token]:
                inverted_index[token].append(doc_label)

print(vocab)
print(inverted_index)

wilayah
kamu
sudah
bebas
covid
-
19
cek
34
kab
kota
zona
hijau
baru
jakarta
-
perintah
rencana
bakal
terap
laku
batas
giat
masyarakat
ppkm
level
3
hitung
24
desember
2021
hingga
2
januari
2021
namun
menteri
sehat
ri
pasti
bijak
ppkm
level
3
ini
masih
dalam
tahap
kaji
turut
direktur
cegah
dan
kendali
sakit
tular
langsung
p2pml
kemenkes
ri
dr
siti
nadia
tarmizi
ppkm
level
3
bakal
terap
jika
kasus
covid
-
19
naik
signifikan
hal
ini
umum
picu
dengan
tingkat
mobilitas
dan
longgar
protokol
sehat
https
health
detik
com
berita
-
detikhealth
d
-
5816690
wilayah
-
kamu
-
sudah
-
bebas
-
covid
-
19
-
cek
-
34
-
kabkota
-
zona
-
hijau
-
terbaru
vaksin
covid
-
19
bakal
rutin
tiap
tahun
gantung
ini
jelas
jakarta
-
beri
booster
atau
dosis
tiga
vaksin
covid
-
19
di
indonesia
rencana
bakal
langsung
januari
2022
lantas
ada
mungkin
vaksinasi
covid
-
19
bakal
harus
laku
tiap
tahun
seperti
vaksinasi
influenza
ketua
satgas
covid
-
19
ikat
dokter
indonesia
idi
prof
zubairi
djoerban
jelas
hingga
kini
belum
ad

In [15]:
def termFrequencyInDoc(vocab, tokenisasi):
    tf_docs = {}
    for doc_id in tokenisasi.keys():
        tf_docs[doc_id] = {}
    for word in vocab:
        for doc_id,doc in tokenisasi.items():
            tf_docs[doc_id][word] = doc.count(word)
    return tf_docs

query = "vaksin corona jakarta"
def termFrequency(vocab, query):
    tf_query = {}
    for word in vocab:
        tf_query[word] = query.count(word)
    return tf_query
tf_query = termFrequency(vocab, query)  

import numpy as np
def wordDocFre(vocab, doc_dict):
    df = {}
    for word in vocab:
        frq = 0
        for doc in doc_dict.values():  # Menggunakan doc_dict.values() untuk mengakses teks dokumen
            if word in doc:
                frq = frq + 1
        df[word] = frq
    return df

def inverseDocFre(vocab, doc_fre, length):
    idf = {}
    for word in vocab:
        idf[word] = 1 + np.log((length + 1) / (doc_fre[word]+1))
    return idf

idf = inverseDocFre(vocab, wordDocFre(vocab,tokenisasi),len(tokenisasi))



In [16]:
import numpy as np
# Term - Query Matrix
TQ = np.zeros((len(vocab), 1)) #hanya 1 query
for word in vocab:
    ind1 = vocab.index(word)
    TQ[ind1][0] = tf_query[word]*idf[word]
print(TQ)

[[0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [1.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.  

In [17]:
# COSINE SIMILARITY
import math
def cosine_sim(vec1, vec2):
    vec1 = list(vec1)
    vec2 = list(vec2)
    dot_prod = 0
    for i, v in enumerate(vec1):
        dot_prod += v * vec2[i]
    mag_1 = math.sqrt(sum([x**2 for x in vec1]))
    mag_2 = math.sqrt(sum([x**2 for x in vec2]))
    return dot_prod / (mag_1 * mag_2)

def tfidf(vocab,tf,idf_scr,doc_dict):
    tf_idf_scr = {}
    for doc_id in doc_dict.keys():
        tf_idf_scr[doc_id] = {}
    for word in vocab:
        for doc_id,doc in doc_dict.items():
            tf_idf_scr[doc_id][word] = tf[doc_id][word] * idf_scr[word]
    return tf_idf_scr

tf_idf = tfidf(vocab, termFrequencyInDoc(vocab, tokenisasi),inverseDocFre(vocab, wordDocFre(vocab, tokenisasi),len(tokenisasi)), tokenisasi)
# Term - Document Matrix
TD = np.zeros((len(vocab), len(tokenisasi)))
for word in vocab:
    for doc_id,doc in tf_idf.items():
        ind1 = vocab.index(word)
        ind2 = list(tf_idf.keys()).index(doc_id)
        TD[ind1][ind2] = tf_idf[doc_id][word]
print(TD)

[[3.38629436 0.         0.         0.         1.69314718]
 [4.19722458 0.         0.         0.         0.        ]
 [3.38629436 0.         3.38629436 0.         0.        ]
 ...
 [0.         0.         0.         0.         2.09861229]
 [0.         0.         0.         0.         2.09861229]
 [0.         0.         0.         0.         2.09861229]]


In [18]:
print(cosine_sim(TQ[:, 0], TD[:, 0])) #query & doc1
print(cosine_sim(TQ[:, 0], TD[:, 1])) #query & doc2
print(cosine_sim(TQ[:, 0], TD[:, 2])) #query & doc3
print(cosine_sim(TQ[:, 0], TD[:, 3])) #query & doc4
print(cosine_sim(TQ[:, 0], TD[:, 4])) #query & doc5

0.013703473266368
0.1536622177883918
0.21014507912913946
0.05492980099719579
0.09069909244814754


In [19]:
from collections import OrderedDict

def exact_top_k(tokenisasi, TD, TQ, k, doc_labels):
    relevance_scores = {}
    i = 0
    for doc_id, doc_label in zip(tokenisasi.keys(), doc_labels):
        relevance_scores[doc_label] = cosine_sim(TQ, TD[:, i])
        i = i + 1
    sorted_value = OrderedDict(sorted(relevance_scores.items(), key=lambda x: x[1], reverse=True))
    top_k = {j: sorted_value[j] for j in list(sorted_value)[:k]}
    return top_k

# Misalkan k = 3, maka:
doc_labels = ["berita1", "berita2", "berita3", "berita4", "berita5"]
top_3 = exact_top_k(tokenisasi, TD, TQ[:, 0], 3, doc_labels)
print(top_3)  # Tiga teratas cosine similarity terbesar

{'berita3': 0.21014507912913946, 'berita2': 0.1536622177883918, 'berita5': 0.09069909244814754}


**Nomor 2**

Lakukan efisiensi dengan menggunakan index elimination sederhana

In [20]:
def index_elim_simple(query, tokenisasi):
    remove_list = []
    new_tokenisasi = {}  # Membuat dictionary baru untuk menyimpan tokenisasi dengan indeks yang dimulai dari 1
    i = 1  # Indeks baru dimulai dari 1

    for doc_id, doc in tokenisasi.items():
        n = 0
        for word in query.split():
            if stemming(word) in doc:
                n += 1

        if n == 0:
            remove_list.append(doc_id)
        else:
            # Menggunakan label "berita" dengan indeks yang dimulai dari 1
            new_tokenisasi[f"berita{i}"] = doc
            i += 1

    for key in remove_list:
        del tokenisasi[key]

    return new_tokenisasi

# Fungsi dummy untuk stemming
def stemming(word):
    # Implementasi stemming sesuai kebutuhan Anda
    # Contoh dummy:
    return word

query = "vaksin corona jakarta"
tokenisasi = index_elim_simple(query, tokenisasi)
print(tokenisasi)

{'berita1': ['wilayah', 'kamu', 'sudah', 'bebas', 'covid', '-', '19', 'cek', '34', 'kab', 'kota', 'zona', 'hijau', 'baru', 'jakarta', '-', 'perintah', 'rencana', 'bakal', 'terap', 'laku', 'batas', 'giat', 'masyarakat', 'ppkm', 'level', '3', 'hitung', '24', 'desember', '2021', 'hingga', '2', 'januari', '2021', 'namun', 'menteri', 'sehat', 'ri', 'pasti', 'bijak', 'ppkm', 'level', '3', 'ini', 'masih', 'dalam', 'tahap', 'kaji', 'turut', 'direktur', 'cegah', 'dan', 'kendali', 'sakit', 'tular', 'langsung', 'p2pml', 'kemenkes', 'ri', 'dr', 'siti', 'nadia', 'tarmizi', 'ppkm', 'level', '3', 'bakal', 'terap', 'jika', 'kasus', 'covid', '-', '19', 'naik', 'signifikan', 'hal', 'ini', 'umum', 'picu', 'dengan', 'tingkat', 'mobilitas', 'dan', 'longgar', 'protokol', 'sehat', 'https', 'health', 'detik', 'com', 'berita', '-', 'detikhealth', 'd', '-', '5816690', 'wilayah', '-', 'kamu', '-', 'sudah', '-', 'bebas', '-', 'covid', '-', '19', '-', 'cek', '-', '34', '-', 'kabkota', '-', 'zona', '-', 'hijau', '-

In [21]:
def elim_query(query, idf_dict, idf_score):
    for term in query.split():  # Memisahkan query menjadi kata-kata
        if idf_dict.get(stemming(term), 0) < idf_score:
            query = query.replace(term + " ", "")
            query = query.replace(term, "")

    return query

# Misalnya digunakan idf_score = 1.5 sebagai treshold
query = "vaksin corona jakarta"
query = elim_query(query, idf, 1.5)
print(query)

vaksin corona 


In [22]:
def create_championlist(inverted_index, tf_idf, r):
    champion_list = {}
    for term in inverted_index.keys():
        weight_scores = {}
        for doc_id,tf in tf_idf.items():
            if tf_idf[doc_id][term]!=0:
                weight_scores[doc_id] = tf_idf[doc_id][term]
    sorted_value = OrderedDict(sorted(weight_scores.items(), key=lambda x: x[1], reverse = True))

    top_r = {j: sorted_value[j] for j in

list(sorted_value)[:r]}

    champion_list[term]=list(top_r.keys())
    return champion_list

r=2
create_championlist(inverted_index, tf_idf, r)

{'mereda': [4]}